import {createTaskUI} from './task-ui.mjs';
import {evidenceDraftKey} from './tasks.mjs';
import {createMotion,installPressFeedback,screenMotionKey} from './motion.mjs';
import {readEntry,applyEntry} from './entry.mjs';
import {track} from './track.mjs';
import {createGuided} from './guided-ui.mjs';
import {finishFieldTask} from './guided.mjs';
import {STATS,QUESTIONS,LESSONS,SAMPLE,LEVELS,EVIDENCE_LABELS} from './content.mjs';
import {blankStore,projectById,createProject,confirmContext,seedSample,submitQuiz,chooseAction,commitEvidence,commitDecision,transact} from './domain.mjs';
import {storageAdapter,interviewAdapter} from './adapters.mjs';
// 점검 도구(AI 응답 지연·실패, 저장 실패 재현)는 주소에 ?lab=1 이 있을 때만 보인다. 일반 사용자 화면에는 노출하지 않는다.
const LAB=typeof location!=='undefined'&&new URLSearchParams(location.search).has('lab');
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();let saveFault=false,aiMode='normal',loadError='',pendingEvidence=null,lastReward=null,toastTimer;
const storage=storageAdapter(localStorage,{fail:()=>saveFault});let state;
try{state=storage.load();}catch(e){loadError=e.message;state=blankStore();}
// SPEC-009 §5: 같은 사이트 랜딩에서 온 경우 문장을 새 프로젝트 입력칸에만 채운다. §4 계측(로컬 버퍼)
const entryInfo=readEntry(location.search,localStorage),TRACK={page:'app'};let lastDone=null;
track('app_open',{from:entryInfo.from},TRACK);
if(!loadError&&applyEntry(state,entryInfo)){try{storage.commit(state);}catch{}track('entry_import',{from:entryInfo.from},TRACK);}
let selectedConcept=state.forms.quiz?.concept||'customer',quizVariant=state.forms.quiz?.variant||0,quizApplication=state.forms.quiz?.application||false,quizResult=null,showAllStats=false;
function restoreQuizResult(){const old=state.events.find(e=>e.key===`attempt:${selectedConcept}:${quizApplication?'application':quizVariant}`);quizResult=old?{...old.result,delta:0,repeated:true}:null;}
if(state.route.view==='quiz')restoreQuizResult();
const statOf=id=>STATS.find(t=>t.id===id),pNow=()=>state.projects.find(p=>p.id===state.route.projectId);
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function update(fn,paint=true){try{if(loadError)throw Error(loadError);const result=transact(state,storage,fn);state=result.store;if(paint)render();return {ok:true,result:result.result};}catch(e){toast(e.message);if(saveFault&&!document.querySelector('.save-error-banner')){const banner=document.createElement('div');banner.className='save-error-banner warning';banner.setAttribute('role','alert');banner.innerHTML='저장 실패 재현 중 · 아직 저장되지 않았어요. <button type="button" class="btn soft" data-action="repair-save">저장 실패 해제</button>';document.body.append(banner);}const status=$('#save-status');if(status)status.textContent='저장되지 않음 · 다시 시도';return {ok:false};}}
function go(view,id=state.route.projectId){pendingEvidence=null;quizResult=null;const r=update(s=>{s.route={view,projectId:id};});if(!r.ok){state.route={view,projectId:id};render();toast('화면만 이동했어요. 저장되지 않은 입력은 새로고침하면 사라질 수 있어요.');}}
function brand(){return `<a class="brand" href="#" data-action="home"><svg class="brandmark" viewBox="0 0 32 35" fill="none" aria-hidden="true"><path d="M4 9 16 30 28 9M16 24V4" stroke="currentColor" stroke-width="3.5" stroke-linecap="round"/><path d="M16 14C7 14 8 4 8 4c7 0 8 5 8 10ZM17 13c0-8 9-9 9-9s0 9-9 9Z" fill="currentColor"/></svg>vencubator<span style="color:#9aa988;font-size:16px">.</span></a>`;}
function mascot(cls=''){return `<svg class="mascot ${cls}" viewBox="0 0 220 240" role="img" aria-label="작은 새싹 창업 부캐"><ellipse cx="111" cy="219" rx="65" ry="10" fill="#bccbab" opacity=".35"/><path d="M108 98C111 60 102 47 91 31" stroke="#79965a" stroke-width="8" fill="none" stroke-linecap="round"/><path d="M104 64C64 63 60 28 64 20c37 1 51 16 40 44Z" fill="#b0c98a"/><path d="M106 73c2-41 41-52 55-48-1 39-23 54-55 48Z" fill="#8faa69"/><path d="M110 62c15-14 25-22 38-26" stroke="#a8c385" stroke-width="2" fill="none"/><path d="M69 98c-8 8-28 17-32 35-5 24 13 35 34 24" fill="#c7da9e" stroke="#a4bc7b" stroke-width="2"/><path d="M153 106c14-12 29-10 34 2 5 11-1 26-18 33" fill="#c7da9e" stroke="#a4bc7b" stroke-width="2"/><path d="M75 187c-5 14-8 25 3 28 13 4 18-13 22-22M128 192c4 14 9 23 20 21 12-3 5-22 0-28" fill="#9eb880"/><path d="M56 124c0-37 23-50 55-50 32 0 59 21 59 64 0 44-23 63-58 63-35 0-56-24-56-77Z" fill="#c9dca7" stroke="#a5be82" stroke-width="2"/><path d="M65 122c3-29 16-39 34-41" stroke="#e1ecc9" stroke-width="6" stroke-linecap="round" fill="none"/><ellipse cx="87" cy="136" rx="5" ry="7" fill="#3b553b"/><ellipse cx="136" cy="136" rx="5" ry="7" fill="#3b553b"/><ellipse cx="78" cy="150" rx="10" ry="5" fill="#e8bba3" opacity=".7"/><ellipse cx="145" cy="150" rx="10" ry="5" fill="#e8bba3" opacity=".7"/><path d="M104 151q8 10 16 0" stroke="#526a43" stroke-width="3" stroke-linecap="round" fill="none"/><path d="m114 174 5-6 5 6-5 6Z" fill="#eff4d9"/><path d="m185 70 2-7 2 7 7 2-7 2-2 7-2-7-7-2Z" fill="#d0b878"/><circle cx="44" cy="82" r="3" fill="#b6c796"/></svg>`;}
function btn(text,action,cls='',attrs=''){return `<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;}
function heading(title,sub,eye='',extra=''){return `<div class="page-heading"><div>${eye?`<div class="eyebrow">${eye}</div>`:''}<h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>${extra}</div>`;}
function field(label,name,value='',placeholder='',type='textarea',attrs=''){return `<div class="field"><label for="f-${name}">${label}</label>${type==='textarea'?`<textarea id="f-${name}" name="${name}" placeholder="${esc(placeholder)}" maxlength="3000" ${attrs}>${esc(value)}</textarea>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${attrs}>`}</div>`;}
function segments(n,before=n){return `<div class="segments" aria-hidden="true">${[1,2,3,4].map(i=>`<span class="${i<=n?'filled':''} ${i>before&&i<=n?'new-segment':''}"></span>`).join('')}</div>`;}
function projectSelector(){return state.projects.length>1?`<select class="project-select" id="project-switch" aria-label="프로젝트 전환">${state.projects.map(p=>`<option value="${p.id}" ${p.id===state.route.projectId?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`:'';}
function navigationIcon(view){
 const paths={dashboard:'<path d="M4 4h6v16H4zM14 4h6v16h-6z"/>',projects:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',learning:'<path d="m12 3 9 9-9 9-9-9Z"/>'};
 return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">'+paths[view]+'</svg>';
}
function shell(content){const view=state.route.view,p=pNow();const titles={projects:'내 프로젝트',new:'새 프로젝트',interview:'아이디어 인터뷰',review:'아이디어 요약',born:'새로운 시작',dashboard:'학습 길',details:'프로젝트 상세',session:'오늘의 학습',fieldtask:'실행 과제',learning:'나의 성장',quiz:'작은 배움',evidence:'관찰 기록',decision:'나의 결정',actions:'다음 행동',journal:'성장 기록',settings:'설정',taskdetail:'지금 할 일'};
return `<div class="layout"><aside class="sidebar">${brand()}<div class="brand-sub">YOUR IDEA, GROWING.</div><div class="nav-title">MY WORKSPACE</div><nav class="nav" aria-label="주요 메뉴">${[['dashboard','◫','학습 길'],['projects','▦','내 프로젝트'],['learning','◇','나의 성장']].map(([v,i,l])=>`<button data-view="${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${navigationIcon(v)}</span>${l}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="side-note"><strong>작은 행동이, 다음 가능성으로.</strong>정답을 찾기보다<br>하나씩 확인하며 자라나요. <span style="color:#8ea766">✧</span></div><div class="profile"><span class="avatar">${esc((state.user?.name||'메')[0])}</span><div>${esc(state.user?.name||'메이커')}<small>나만의 창업 여정</small></div></div></div></aside><div class="workspace"><header class="topbar"><div class="breadcrumb">워크스페이스 <span>/</span> <strong>${titles[view]||'내 프로젝트'}</strong></div><div class="top-actions"><span class="save-status" id="save-status">이 브라우저에 저장됨</span><span class="pill"><i class="dot"></i>체험판</span><button class="iconbtn" data-view="settings" aria-label="알림 설정 미리보기">♧</button></div></header><main class="main" id="main" tabindex="-1">${content}<footer class="footer-note"><span><strong>조금씩, 더 분명한 아이디어로.</strong> 정리한 가설은 실제 고객에게 확인해야 해요.</span><span>VENCUBATOR · 체험판</span></footer></main></div></div>`;}
function welcome(){return `<div class="welcome"><header class="welcome-header">${brand()}<span class="pill"><i class="dot"></i>체험판</span></header><main class="welcome-body" id="main"><section><div class="eyebrow">A SMALL IDEA. A NEW POSSIBILITY.</div><h1>당신의 아이디어에,<br><em>다음 한 걸음.</em></h1><p class="lead">막연했던 생각을 나만의 창업 부캐로.<br>작게 배우고, 직접 확인하며<br>아이디어와 함께 자라보세요.</p>${loadError?`<div class="warning error">${esc(loadError)}${btn('기존 데이터 백업','backup','link')}${btn('기록 지우고 새로 시작','reset','link')}</div>`:''}<form id="login-form"><label for="maker-name">어떤 이름으로 시작할까요?</label><input id="maker-name" name="name" placeholder="예: 메이커" maxlength="24" autocomplete="nickname"><div class="button-row"><button class="btn primary large" type="submit" ${loadError?'disabled':''}>내 아이디어 키우기 <span class="arrow">↗</span></button>${btn('TeamUp 샘플 둘러보기','sample','link',loadError?'disabled':'')}</div></form><p class="small muted">실제 회원가입 없이 체험해요. AI 대화와 고객 관찰은 가상 예시이며, 기록은 이 브라우저에만 저장됩니다.</p></section><div class="welcome-art"><span class="orbit-label one">◎ 고객을 조금 더 이해했어요</span>${mascot('floating')}<span class="orbit-label two">✧ 나의 첫 가설</span><div class="art-caption"><strong>아직 작은 생각이어도 괜찮아요.</strong><span>하나의 질문에서 시작하는 창업 여정</span></div></div></main></div>`;}
function details(){const p=pNow();if(!p)return projects();if(!p.context)return `<div class="narrow panel"><h1>${esc(p.name)}</h1><p>${esc(p.description)}</p><p class="concept-copy">배우면서 아이디어를 채워가요. 아직 확정한 사업 가설은 없어요.</p>${btn('학습 길로 돌아가기','dashboard','primary')}${btn('아이디어 더 정리하기','interview','link')}</div>`;const real=p.evidence.filter(e=>e.scopeVersion===p.scopeVersion&&e.kind==='field');const refuted=Object.values(p.stats).some(s=>['refuted','mixed'].includes(s.state));const action=p.nextAction?.status==='planned'?p.nextAction.title:refuted?'다른 단서에서, 다음 방향 찾기':'고객 한 명의 최근 경험 들어보기';
return `${heading(`${esc(state.user.name)}님, 오늘은 한 걸음만.`, '작은 질문 하나가 아이디어를 더 분명하게 만들어요.','YOUR GROWING SPACE',projectSelector())}${refuted?`<div class="warning">기존 가설과 다른 단서가 있어요. 탐구 이력은 자랐지만, 현재 가설은 다시 살펴봐야 해요. ${btn('근거 살펴보기','journal','link')}</div>`:''}<div class="dashboard-grid"><section class="character-card"><div class="decor"></div><div class="character-header"><span class="eyebrow">MY VENTURE</span><span class="pill">✧ ${real.length?'현장을 알아가는 중':'첫 가설을 정리했어요'}</span></div><div class="character-middle"><div class="character-info"><h2 class="character-name">${esc(p.name)}</h2><p class="text-wrap">${esc(p.description)}</p></div>${mascot('floating')}</div><div class="character-footer"><span class="pill">부캐 · 내 프로젝트</span><span>아직 작은 가능성, 함께 키워가요.</span></div></section><section class="mission-card"><div class="mission-top"><span>YOUR NEXT SMALL STEP</span><span class="tag">고객 이해</span></div><h2>${esc(action)}</h2><p>${refuted?'예상과 달랐던 점을 정리하고, 유지하거나 바꿀 방향을 직접 선택해 보세요.':'생각했던 불편이 정말 있는지, 최근에 겪었던 상황부터 물어보세요.'}</p><div class="mission-meta"><span>◷ 준비 3분</span><span>◎ 관찰 1건부터</span></div>${btn(`다음 행동 살펴보기 <span class="arrow">→</span>`,'actions','primary wide')}</section></div><div class="section-head"><h2>아이디어는 이렇게 자라고 있어요</h2>${btn(showAllStats?'간단히 보기 −':'7개 영역 모두 보기 +','toggle-stats','link')}</div><div class="stats-grid">${(showAllStats?STATS:STATS.filter(t=>['customer','product','strategy'].includes(t.id))).map(t=>statCard(t,p.stats[t.id])).join('')}</div><p class="unit-note">탐구 단계는 알아보고 판단한 과정이에요. 사업 성공률이나 시장 검증 완료를 뜻하지 않아요.</p><div class="bottom-grid"><section><div class="section-head"><h2>최근에 달라진 것</h2>${btn('전체 기록 →','journal','link')}</div><div class="journal-preview"><div class="timeline-row"><i class="timeline-dot"></i><div><strong>${p.decisions.length?'근거를 바탕으로 다음 방향을 선택했어요':real.length?'고객에 대한 새로운 단서를 남겼어요':'누구의 어떤 문제인지 정리했어요'}</strong><p>${p.decisions.length?esc(p.decisions.at(-1).rationale):esc(p.context.customer)}</p><time>내 아이디어에 남은 작은 변화 · ${p.revision}번째 저장</time></div></div></div></section><section><div class="section-head"><h2>지금 필요한 작은 배움</h2><span>약 2분</span></div><div class="learning-preview"><div class="book-icon">a</div><div><div class="eyebrow">CUSTOMER DISCOVERY</div><h3>좋다는 말보다, 지난 행동</h3>${btn('고객에게 질문하는 법 배우기 ↗','learn-customer','link')}</div></div></section></div><div class="button-row">${btn('아이디어 요약 보기','review','link')}${btn('관찰 기록하기','evidence','link')}${btn('나의 결정 남기기','decision','link')}</div>`;}
function statCard(t,s){return `<article class="stat-card" style="--stat:${t.color}"><div class="stat-header"><span class="stat-name"><span class="stat-symbol" style="color:${t.color}">${t.icon}</span>${t.name}</span><span class="stat-stage">${s.milestone?`탐구 ${s.milestone}단계`:'시작 전'}</span></div><strong>${t.id==='strategy'&&s.milestone===2?'결정 기록':LEVELS[s.milestone]}</strong>${segments(s.milestone)}<span class="small ${s.state==='refuted'?'danger':'muted'}">${EVIDENCE_LABELS[s.state]}</span>${s.highest>s.milestone?`<p class="small muted">이전 가설 최고 ${s.highest}단계 · 새 범위 확인 중</p>`:''}</article>`;}
function projects(){return `${heading('내 아이디어, 나의 가능성.','프로젝트마다 다른 질문, 다른 성장의 이야기가 쌓여요.','MY VENTURES',btn('+ 새 프로젝트','new','primary'))}${state.projects.length?`<div class="projects-grid">${state.projects.map(p=>`<button class="project-tile" data-action="open-project" data-id="${p.id}"><div class="tile-top"><span class="pill">${p.context?'가설 탐구 중':'아이디어 정리 중'}</span>${mascot()}</div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="tile-foot"><span>${p.context?'나의 창업 부캐':'저장한 질문부터 이어갈 수 있어요'}</span><span>이어가기 →</span></div></button>`).join('')}</div>`:`<section class="panel empty">${mascot()}<h2>어떤 아이디어를 키워볼까요?</h2><p>한 문장이면 충분해요.<br>아직 이름이 없어도, 수익모델을 몰라도 괜찮아요.</p><div class="button-row" style="justify-content:center">${btn('첫 프로젝트 만들기 ↗','new','primary')}${btn('샘플 먼저 둘러보기','sample','soft')}</div></section>`}`;}
function newProject(){const d=state.forms.new??{};return `<div class="narrow">${heading('작은 생각에서 시작해요.','완벽한 사업계획보다, 지금 떠오른 한 문장이면 돼요.','NEW POSSIBILITY')}${state.forms.entry?.pending?'<div class="hint-box entry-hint" role="status">소개 페이지의 카드에서 쓴 문장을 가져왔어요. 그대로 쓰거나 고쳐 써도 괜찮아요. 퀴즈·관찰·결정은 여기서 새로 시작해요.</div>':''}<form id="new-form" class="panel" data-draft="new">${field('어떤 서비스를 만들고 싶나요?','description',d.description,'예: 대학생들이 시간과 역할이 맞는 팀플 동료를 찾는 서비스','textarea','required')}${field('프로젝트 이름 · 선택','name',d.name,'아직은 가칭이어도 괜찮아요','text','maxlength="40"')}<div class="hint-box">짧게 배우고, 문제를 풀고, 내 아이디어에 써봐요.<br>모르는 내용은 배우면서 하나씩 채우면 돼요.</div><div class="button-row"><button class="btn primary" type="submit">나의 학습 길 시작 →</button>${btn('가상 예시 넣기','fill-new','link')}</div></form></div>`;}
const interviewRequests=new Map();
function loadInterview(){
 const p=pNow(),key=JSON.stringify([p.id,p.step,aiMode]);
 let request=interviewRequests.get(key);
 if(!request){
  request={status:'pending',message:'',promise:null};interviewRequests.set(key,request);
  request.promise=interviewAdapter(p.step,{mode:aiMode}).then(()=>{request.status='ready';}).catch(e=>{request.status='error';request.message=e.message;});
 }
 const group=$('#question-load'),notice=$('#ai-notice');if(!group)return;
 const finish=()=>{
  if(!group.isConnected)return;
  group.setAttribute('aria-busy','false');group.querySelector('.question-skeleton')?.remove();
  notice.textContent=request.status==='error'?request.message:'질문이 준비됐어요.';
  notice.classList.toggle('error',request.status==='error');
 };
 if(request.status!=='pending'){finish();return;}
 group.setAttribute('aria-busy','true');notice.textContent='질문을 준비하고 있어요…';
 group.insertAdjacentHTML('beforeend','<div class="question-skeleton" aria-hidden="true"><span class="skeleton-line title"></span><span class="skeleton-line"></span><span class="skeleton-line short"></span></div>');
 request.promise.then(finish);
}
function interview(){const p=pNow();if(!p)return projects();const q=QUESTIONS[p.step];return `<div class="narrow">${heading('이야기하며, 조금 더 구체적으로.','답하는 만큼 아이디어가 정리돼요. 언제든 이어서 할 수 있어요.','IDEA INTERVIEW')}<div class="interview-progress"><span>${p.step+1} / ${QUESTIONS.length}</span><div class="segments">${QUESTIONS.map((_,i)=>`<span class="${i<=p.step?'filled':''}"></span>`).join('')}</div><span>${q.label}</span></div><section class="panel"><div class="coach-row"><span class="coach-icon">✧</span>아이디어 코파일럿 <span class="pill">정해진 질문 대역</span></div><div id="question-load" class="question-load-group" aria-busy="false"><div class="question-copy"><h2 class="interview-question">${q.question}</h2><p class="lesson-summary">${q.why}</p></div></div><p id="ai-notice" class="question-load-status" role="status"></p><form id="interview-form" data-interview="${q.key}"><div class="field"><label for="answer">나의 생각</label><textarea id="answer" name="answer" placeholder="${q.placeholder}" maxlength="3000">${esc(p.draft[q.key])}</textarea></div><button class="suggestion" type="button" data-action="interview-example">가상 예시 참고 · ${q.placeholder}</button><div class="interview-bottom"><div>${btn('← 이전','previous','link',p.step===0?'disabled':'')}${btn('아직 모르겠어요','unknown','link')}</div><button class="btn primary" type="submit">${p.step===5?'요약 확인하기':'다음 질문'} →</button></div></form></section><div class="button-row">${btn('저장하고 나중에','projects','link')}<span class="save-status">입력한 답변을 이 브라우저에 저장해요.</span></div></div>`;}
function review(){const p=pNow();if(!p)return projects();const d=p.draft;return `<div class="narrow">${heading('이렇게 이해했어요.','틀린 부분은 고쳐주세요. 확인해도 아직은 검증할 가설이에요.','YOUR IDEA, CLEARER')}<form id="review-form" class="panel"><div class="detail-bar"><h2>${esc(p.name)}</h2><span class="pill">사용자 확인 전 초안</span></div>${p.context?'<div class="warning">내용을 바꾸면 새로운 가설 범위로 저장해요. 이전 탐구 이력은 남고 현재 근거는 다시 확인해요.</div>':''}${QUESTIONS.map(q=>`<div class="context-row"><label for="review-${q.key}">${q.label}</label><textarea id="review-${q.key}" name="${q.key}" maxlength="3000">${esc(d[q.key]||'아직 모르겠어요')}</textarea></div>`).join('')}<details class="screen-help"><summary>아직 모르는 것도 남겨둘게요</summary><p>시장 규모 · 수익모델 · 경쟁 비교는 아직 미확인입니다.<br>이 요약은 고객이 검증한 사실이 아닌 나의 가설입니다.</p></details><div class="button-row"><button class="btn primary" type="submit">이 내용으로 ${p.context?'가설 수정':'부캐 만들기'} →</button>${btn('돌아가기','dashboard','link')}</div></form></div>`;}
function born(){const p=pNow();return `<div class="narrow born"><div class="eyebrow">A NEW BEGINNING</div>${mascot('floating')}<h1>${esc(p?.name)}, 첫걸음을 뗐어요.</h1><p>막연했던 생각에 고객과 문제가 생겼어요.<br>이제, 그 생각을 실제로 확인할 차례예요.</p><div class="button-row">${btn('내 프로젝트 만나기 →','dashboard','primary large')}</div><p class="screen-help">부캐는 내가 키우는 프로젝트예요. 생성 연출에는 추가 점수가 없어요.</p></div>`;}
function learning(){const ms=Object.values(state.mastery);return `${heading('아이디어가 바뀌어도, 배움은 남아요.','프로젝트를 키우며 내가 이해하고 적용한 것들을 모았어요.','MY FOUNDER JOURNEY')}<div class="summary-strip"><div><strong>${ms.filter(m=>m.understood).length}<span> / 7</span></strong><span>이해를 확인한 개념</span></div><div><strong>${ms.filter(m=>m.applied).length}</strong><span>새 상황에 적용한 개념</span></div><div><strong>${ms.reduce((n,m)=>n+m.xp,0)}</strong><span>학습 XP · 능력 인증은 아니에요</span></div></div><div class="knowledge-grid">${LESSONS.map(l=>{const t=statOf(l.stat),m=state.mastery[l.id];return `<article class="knowledge-card"><div class="stat-header"><span class="stat-symbol" style="color:${t.color}">${t.icon}</span><span class="pill">${m?.applied?'적용 확인':m?.understood?'이해 확인':m?.review?'복습 중':'새로운 배움'}</span></div><div class="eyebrow">${t.name}</div><h3>${l.title}</h3><p>${t.description}</p><div class="button-row">${btn(m?.understood?'다시 살펴보기 →':'짧게 배우기 →','lesson','link',`data-concept="${l.id}"`)}${m?.understood?btn('새 상황에 적용','application','soft',`data-concept="${l.id}"`):''}</div></article>`;}).join('')}</div>`;}
function choices(q,name,options){return `<fieldset class="choice-set"><legend>${q}</legend>${options.map((o,i)=>`<label class="choice"><input type="radio" name="${name}" value="${i}" required ${quizResult?'disabled':''}><span>${esc(o)}</span></label>`).join('')}</fieldset>`;}
function quiz(){const l=LESSONS.find(l=>l.id===selectedConcept),q=quizApplication?l.application:l.variants[quizVariant];return `<div class="narrow">${heading(l.title,quizApplication?'다른 아이디어에도 같은 원리를 적용해 볼까요?':'지금 내 아이디어에 필요한 지식, 2분이면 충분해요.',statOf(l.stat).name)}<section class="panel"><span class="question-number">${quizApplication?'새 상황에 적용':'짧은 배움'} · ${quizVariant+1}</span><p class="lesson-summary">${l.summary}</p><p class="small muted">학습 근거: ${l.source}</p><form id="quiz-form">${choices(q.question,'choice',q.options)}${choices('그 답을 고른 이유는 무엇인가요?','reason',q.reasons)}<button class="btn primary" type="submit" ${quizResult?'disabled':''}>${quizApplication?'적용 확인':'답 확인하기'}</button></form>${quizResult?`<div class="quiz-result ${quizResult.correct?'':'wrong'}" role="status"><h3>${quizResult.correct?'개념을 잘 짚었어요.':'괜찮아요. 여기서 하나 배워봐요.'}</h3><p>${quizResult.why}</p><p>${quizResult.delta?`내 학습 +${quizResult.delta} XP · 프로젝트 근거는 변하지 않았어요.`:quizResult.repeated?'이미 확인한 문항이에요. 추가 XP는 없어요.':'설명을 읽고 새 문제에서 확인해 보세요. 읽기만으로 XP가 오르지 않아요.'}</p><div class="button-row">${!quizApplication&&quizVariant===0?btn('새 문제로 확인하기','retry-quiz','soft'):''}${state.mastery[l.id]?.understood&&!quizApplication?btn('새 상황에 적용하기','application','soft',`data-concept="${l.id}"`):''}${btn('내 학습으로','learning','link')}</div></div>`:''}</section><div class="button-row">${btn('← 내 학습','learning','link')}${pNow()?.context?btn('내 프로젝트에 관찰 남기기 →','evidence','link'):''}</div></div>`;}
function evidence(){const p=pNow();if(!p?.context)return projects();const d=p.uiDraft.evidence??{};if(pendingEvidence)return `<div class="narrow">${heading('관찰과 나의 해석을 확인해요.','아직 저장하지 않았어요. 확인한 뒤에만 기록과 성장에 반영돼요.','REVIEW YOUR EVIDENCE')}<section class="panel">${[['근거 종류',pendingEvidence.kind==='field'?'가상 현장 관찰':'AI 시뮬레이션'],['영역',statOf(pendingEvidence.stat).name],['확인한 질문·가설',pendingEvidence.claim],['관찰한 내용',pendingEvidence.summary],['나의 해석',pendingEvidence.interpretation],['현재 가설',EVIDENCE_LABELS[pendingEvidence.assessment]],['출처와 한계',`${pendingEvidence.source} · ${pendingEvidence.limitations}`]].map(([a,b])=>`<div class="context-row"><dt>${a}</dt><dd>${esc(b)}</dd></div>`).join('')}<div class="button-row">${btn('확인하고 기록하기','confirm-evidence','primary')}${btn('내용 수정','edit-evidence','link')}</div></section></div>`;
return `<div class="narrow">${heading('새롭게 알게 된 것을 남겨요.','좋은 반응도, 예상과 다른 반응도 다음 결정의 단서예요.','FIELD NOTES')}<div class="warning">체험판이라 기록은 이 브라우저에만 남아요. 실제 고객의 이름·연락처 같은 개인정보는 적지 마세요.</div><form id="evidence-form" class="panel" data-project-draft="evidence"><input type="hidden" name="taskId" value="${esc(d.taskId||'')}"><div class="form-grid"><div class="field"><label for="ev-kind">근거 종류</label><select id="ev-kind" name="kind"><option value="field" ${d.kind!=='simulation'?'selected':''}>가상 현장 관찰</option><option value="simulation" ${d.kind==='simulation'?'selected':''}>AI 시뮬레이션 (검증 아님)</option></select></div><div class="field"><label for="ev-stat">살펴본 영역</label><select id="ev-stat" name="stat">${STATS.filter(t=>t.id!=='strategy').map(t=>`<option value="${t.id}" ${d.stat===t.id?'selected':''}>${t.name}</option>`).join('')}</select></div>${field('출처 · 익명 구분','source',d.source,'예: 가상 고객 A','text','required')}${field('관찰 날짜','date',d.date||new Date().toISOString().slice(0,10),'','date','required')}${field('어떻게 확인했나요?','method',d.method,'예: 최근 팀플 경험을 묻는 인터뷰','text','required')}<div class="field"><label for="assessment">기존 가설과 비교하면?</label><select id="assessment" name="assessment"><option value="mixed" ${d.assessment==='mixed'?'selected':''}>엇갈리는 단서</option><option value="supported" ${d.assessment==='supported'?'selected':''}>가설을 지지하는 단서</option><option value="refuted" ${d.assessment==='refuted'?'selected':''}>가설과 다른 단서</option></select></div><div class="full">${field('이 관찰로 확인하는 가설','claim',d.claim||p.context.problem,'해당 영역에서 무엇을 확인하려 하나요?','textarea','required')}${field('무엇을 관찰했나요?','summary',d.summary,'관찰한 말과 행동을 적어주세요.','textarea','required')}${field('나는 어떻게 해석했나요?','interpretation',d.interpretation,'관찰한 내용과 나의 해석을 구분해요.','textarea','required')}${field('이 근거의 한계는?','limitations',d.limitations,'예: 가상 사례이며, 한 사람의 경험이에요.','text','required')}${field('다른 관찰과 비교 · 선택','comparison',d.comparison,'독립적인 관찰이 있다면 일치/불일치와 다른 해석을 적어주세요.')}</div></div><div class="button-row"><button class="btn primary" type="submit">기록 내용 확인 →</button>${btn('반박 사례 예시 넣기','fill-evidence','link')}</div></form></div>`;}
function decision(){const p=pNow();if(!p?.context)return projects();const d=p.uiDraft.decision??{};return `<div class="narrow">${heading('다음 방향은, 내가 선택해요.','근거를 보고 어떤 생각이 달라졌는지 남겨보세요.','MY DECISION')}<form id="decision-form" class="panel" data-project-draft="decision"><div class="hint-box">현재 가설: ${esc(p.context.problem)}<br>현재 범위의 가상 현장 관찰: ${p.evidence.filter(e=>e.kind==='field'&&e.scopeVersion===p.scopeVersion).length}건</div><div class="field"><label for="decision-choice">어떤 방향을 선택하나요?</label><select id="decision-choice" name="choice"><option value="change">가설 또는 방법을 바꿀게요</option><option value="continue" ${d.choice==='continue'?'selected':''}>계속 확인할게요</option><option value="pause" ${d.choice==='pause'?'selected':''}>잠시 보류할게요</option></select></div>${field('그렇게 결정한 이유','rationale',d.rationale,'어떤 근거가 판단에 영향을 주었나요?','textarea','required')}${field('실험 전 기준과 비교 · 선택','comparison',d.comparison,p.nextAction?.criterion||'사전 기준을 정하지 않았다면 비워둬도 돼요.')}${field('다음에 할 작은 행동','nextAction',d.nextAction,'예: 팀 안에서 역할을 합의하는 방법을 먼저 확인해요.','text','required')}<div class="button-row"><button class="btn primary" type="submit">내 결정 저장하기</button>${btn('근거 먼저 남기기','evidence','link')}</div></form></div>`;}
function actions(){const p=pNow();if(!p?.context)return projects();const d=p.uiDraft.action??{};return `<div class="narrow">${heading('오늘은, 이만큼만 해볼까요?','지금 가장 중요한 불확실성부터 하나씩 살펴봐요.','YOUR NEXT STEP')}<article class="action-card recommended"><span class="tag">지금 추천 · 고객 이해</span><h3>고객 한 명에게 최근 경험 물어보기</h3><p>${esc(p.context.customer)}에게 문제를 겪었던 순간과 현재 해결 방법을 물어보세요. 어떤 결과가 나오면 생각을 바꿀지도 먼저 정해요.</p><div class="button-row">${btn('이 행동 선택하기','suggest-action','primary')}${btn('질문하는 법 먼저 배우기','learn-customer','link')}</div></article><form id="action-form" class="panel" data-project-draft="action">${field('내가 할 작은 행동','title',d.title||p.nextAction?.title||'','예: 고객 한 명에게 최근 팀플 경험 물어보기','text','required')}${field('어떤 결과가 나오면 생각을 바꿀까요?','criterion',d.criterion||p.nextAction?.criterion||'','예: 모집보다 다른 불편이 크다면 문제 가설을 수정한다.','textarea','required')}<div class="button-row"><button class="btn primary" type="submit">나의 다음 행동으로 저장</button>${btn('지금은 보류','defer-action','link')}</div></form><div class="action-card" style="margin-top:18px"><h3>지금 시간이 조금 부족한가요?</h3><p>대화할 사람 한 명을 떠올리는 것부터 시작해도 괜찮아요. 알림은 원하는 시각에만.</p><div class="button-row">${btn('알림 미리보기','settings','soft')}${btn('관찰 결과 기록하기 →','evidence','link')}</div></div></div>`;}
function journal(){const p=pNow();if(!p?.context)return projects();return `${heading('작은 변화가 쌓이는 곳.','무엇을 알게 됐고, 그래서 어떤 선택을 했는지.','GROWTH JOURNAL',projectSelector())}<div class="button-row" style="margin:0 0 22px">${btn('+ 관찰 기록','evidence','primary')}${btn('나의 결정 남기기','decision','soft')}${btn('요약 보기','review','link')}</div><div class="history">${[...p.decisions].reverse().map(d=>`<article class="history-item"><div class="history-meta"><span class="pill">나의 결정</span><span>${new Date(d.time).toLocaleDateString('ko-KR')}</span></div><h3>${{change:'다른 방향으로 살펴보기',continue:'계속 확인하기',pause:'잠시 보류하기'}[d.choice]}</h3><p>${esc(d.rationale)}</p><p>다음 행동 · ${esc(d.nextAction)}</p></article>`).join('')}${[...p.evidence].reverse().map(e=>`<article class="history-item"><div class="history-meta"><span class="pill ${e.assessment==='refuted'?'warn':''}">${e.kind==='simulation'?'AI 시뮬레이션 · 검증 아님':'가상 현장 관찰'}</span><span>${esc(e.date)} · ${esc(e.source)}</span><span>${e.scopeVersion===p.scopeVersion?'현재 가설 범위':'이전 가설의 기록'}</span></div><h3>${esc(e.summary)}</h3><p>나의 해석 · ${esc(e.interpretation)}</p><p>한계 · ${esc(e.limitations)}</p><p>${EVIDENCE_LABELS[e.assessment]}</p></article>`).join('')}<article class="history-item"><div class="history-meta"><span class="pill">가설 정리</span><span>실제 검증 전</span></div><h3>아이디어에 첫 모양이 생겼어요.</h3><p>${esc(p.context.customer)} · ${esc(p.context.problem)}</p></article></div>`;}
function settings(){return `<div class="narrow">${heading('나에게 맞는 속도로.','알림과 화면 경험을 편안하게 조절하세요.','PREFERENCES')}<section class="panel"><h2>나의 리듬</h2><div class="toggle-row"><label for="reminder">다음 행동 알림 미리보기<small>체험판에서는 실제 알림을 보내지 않아요.</small></label><input id="reminder" type="checkbox" data-pref="reminder" ${state.preferences.reminder?'checked':''}></div><div class="field"><label for="reminder-time">알림 시각 · 매주 화요일과 목요일</label><input type="time" id="reminder-time" data-pref="time" value="${esc(state.preferences.time)}"></div>${state.preferences.reminder?`<div class="hint-box">알림 미리보기 · ${esc(state.preferences.time)}<br>${esc(pNow()?.name||'내 프로젝트')}: 지난번 행동의 결과를 남기고 다음 실험을 골라보세요.</div>`:''}<div class="toggle-row"><label for="reduced-motion">움직임 줄이기<small>기기의 모션 감소 설정도 함께 존중해요.</small></label><input id="reduced-motion" type="checkbox" data-pref="reducedMotion" ${state.preferences.reducedMotion?'checked':''}></div></section><section class="panel"><h2>내 기록</h2><p class="screen-help">체험판의 기록은 서버로 보내지 않고 이 브라우저에만 저장돼요. 기록을 따로 보관하려면 백업 파일을 받아 두세요.</p>${LAB?`<details class="screen-help" open><summary>점검 도구</summary><div class="field"><label for="ai-mode">인터뷰 대역 응답</label><select id="ai-mode"><option value="normal" ${aiMode==='normal'?'selected':''}>정상</option><option value="slow" ${aiMode==='slow'?'selected':''}>지연 재현 (1.5초)</option><option value="error" ${aiMode==='error'?'selected':''}>실패 재현 · 기본 질문 사용</option></select></div><div class="toggle-row"><label for="save-fault">저장 실패 재현<small>입력은 남기고, 저장과 성장 확정을 막아요.</small></label><input type="checkbox" id="save-fault" ${saveFault?'checked':''}></div></details>`:''}<div class="button-row">${btn('저장 데이터 백업','backup','soft')}${btn('처음 화면으로 나가기','logout','link')}</div><details class="screen-help"><summary>기록 모두 지우기</summary><p>이 브라우저에 저장된 Vencubator 기록을 모두 지워요. 지운 기록은 되돌릴 수 없으니 먼저 백업 파일을 받아 두세요.</p>${btn('기록 모두 지우기','reset','link danger')}</details></section></div>`;}
function reward(title,message,rows=[]){lastReward={title,message,rows};const dialog=document.createElement('dialog');dialog.id='reward';dialog.innerHTML=`<div class="reward-content"><div class="reward-spark" aria-hidden="true">✧</div><h2 id="reward-title">${esc(title)}</h2><p>${esc(message)}</p>${rows.map(r=>`<div class="reward-row" style="--stat:${statOf(r.stat)?.color||'#648652'}"><header><strong>${r.subject==='user'?'내 학습':'내 프로젝트'} · ${statOf(r.stat)?.name||''}</strong><span>${r.delta?`+${r.delta} XP`:`${r.before} → ${r.after}단계`}</span></header>${r.delta?'':segments(r.after,r.before)}<small>${r.subject==='user'?'배움을 확인했어요. 프로젝트의 근거는 별도예요.':'탐구 과정의 진전이에요. 사업 성공률이 아니에요.'}</small></div>`).join('')}<div class="button-row"><button class="btn primary wide" data-action="close-reward" autofocus>변화 확인했어요</button><button class="btn link" data-action="replay-reward">성장 연출 다시 보기</button></div></div>`;dialog.setAttribute('aria-labelledby','reward-title');document.body.append(dialog);const focusBefore=document.activeElement;dialog.addEventListener('close',()=>{dialog.remove();focusBefore?.isConnected&&focusBefore.focus();});dialog.showModal();}
let renderedScreen='';
const paintMotion=createMotion();installPressFeedback();
function render(){
 const done=state.projects.reduce((n,p)=>n+Object.values(p.learningRuns||{}).filter(r=>r?.completedAt).length,0);if(lastDone!==null&&done>lastDone)track('lesson_complete',{count:done},TRACK);lastDone=done;
 const screen=screenMotionKey(state,{variant:quizVariant,application:quizApplication,preview:!!pendingEvidence});
 const changed=screen!==renderedScreen;renderedScreen=screen;
 document.body.classList.toggle('reduce-motion',state.preferences.reducedMotion);
 if(!state.user){$('#app').innerHTML=welcome();paintMotion(screen);return;}
 const views={projects,new:newProject,interview,review,born,dashboard:guided.home,session:guided.session,fieldtask:guided.task,taskdetail:taskUI.detail,details,learning,quiz,evidence:()=>!pendingEvidence&&(state.route.fieldTaskId||pNow()?.uiDraft.evidence?.taskId)?guided.reflection():evidence(),decision,actions,journal,settings};
 document.body.classList.toggle('has-task-fab',!!pNow()&&['dashboard','details'].includes(state.route.view));
 const taskIntro=['dashboard','details'].includes(state.route.view)?taskUI.preview():'';
 $('#app').innerHTML=shell(taskIntro+(views[state.route.view]??projects)())+taskUI.floating();
 if(changed){window.scrollTo(0,0);const heading=$('main h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
 if(state.route.view==='interview')loadInterview();
 paintMotion(screen);
}
const guided=createGuided({getState:()=>state,update,go,esc,mascot,field,toast});
const taskUI=createTaskUI({getState:()=>state,update,esc,toast});
const formData=f=>Object.fromEntries(new FormData(f));
document.addEventListener('input',e=>{const el=e.target,form=el.closest('form');if(!form)return;if(form.dataset.draft){update(s=>{s.forms[form.dataset.draft]=formData(form);},false);}if(form.dataset.projectDraft){const id=state.route.projectId;update(s=>{projectById(s,id).uiDraft[form.dataset.projectDraft]=formData(form);},false);}if(form.dataset.interview){update(s=>{projectById(s,state.route.projectId).draft[form.dataset.interview]=el.value;},false);}if(form.id==='review-form'){update(s=>{projectById(s,state.route.projectId).draft={...formData(form)};},false);}});
document.addEventListener('change',e=>{const el=e.target;taskUI.change(el);if(el.dataset.pref){update(s=>{s.preferences[el.dataset.pref]=el.type==='checkbox'?el.checked:el.value;});}if(el.id==='ai-mode'){aiMode=el.value;toast('인터뷰 대역 설정을 바꿨어요.');}if(el.id==='save-fault'){saveFault=el.checked;toast(saveFault?'저장 실패를 재현해요. 이 설정은 언제든 해제할 수 있어요.':'저장을 다시 사용할 수 있어요.');}if(el.id==='project-switch'){const p=state.projects.find(p=>p.id===el.value);go('dashboard',el.value);}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=formData(f),p=pNow();if(taskUI.submit(f,d)||guided.submit(f,d))return;
 if(f.id==='login-form')update(s=>{s.user={id:'demo-user',name:cleanName(d.name)};s.route={view:s.forms.entry?.pending||!s.projects.length?'new':'dashboard',projectId:s.projects[0]?.id??null};});
 if(f.id==='new-form'){const id=state.forms.newId||uid();const imported=!!state.forms.entry?.pending,from=state.forms.entry?.from||entryInfo.from;const r=update(s=>{createProject(s,{id,...d});s.forms.new={};s.forms.newId=null;if(s.forms.entry)s.forms.entry.pending=false;s.route={view:'dashboard',projectId:id};});if(r.ok)track('project_create',{from,imported},TRACK);}
 if(f.id==='interview-form'){update(s=>{const project=projectById(s,p.id);project.draft[QUESTIONS[project.step].key]=d.answer.trim()||'아직 모르겠어요';if(project.step===5)s.route.view='review';else project.step++;});}
 if(f.id==='review-form'){const first=!p.context;const r=update(s=>{const rows=confirmContext(s,p.id,d);s.route.view=first?'born':'dashboard';return rows;});if(r.ok&&!first)reward('아이디어 요약을 갱신했어요.','새 가설 범위의 근거는 다시 확인해요. 이전 탐구 이력은 남아 있어요.',r.result);}
 if(f.id==='quiz-form'){const r=update(s=>submitQuiz(s,{concept:selectedConcept,variant:quizVariant,choice:d.choice,reason:d.reason,application:quizApplication}),false);if(r.ok){quizResult=r.result;render();if(r.result.delta)reward('내 배움이 한 걸음 자랐어요.','개념을 이해하고 다음 행동에 연결할 준비를 했어요.',[{subject:'user',stat:selectedConcept,delta:r.result.delta}]);}}
 if(f.id==='evidence-form'){pendingEvidence={...d,id:uid()};render();}
 if(f.id==='decision-form'){const r=update(s=>{const rows=commitDecision(s,p.id,{...d,id:uid()});projectById(s,p.id).uiDraft.decision={};s.route.view='journal';return rows;});if(r.ok)reward('다음 방향을 직접 선택했어요.','어떤 근거로 생각을 바꿨는지 기록에 남겼어요.',r.result);}
 if(f.id==='action-form'){const r=update(s=>{chooseAction(s,p.id,d);s.route.view='dashboard';});if(r.ok)toast('다음 행동과 판단 기준을 저장했어요. 선택만으로 점수는 오르지 않아요.');}
});
function cleanName(name){return String(name||'메이커').trim().slice(0,24)||'메이커';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-view],[data-guide],[data-task]');if(!b)return;e.preventDefault();if(taskUI.click(b)||guided.click(b))return;const a=b.dataset.action,p=pNow();if(a==='repair-save'){saveFault=false;b.closest('.save-error-banner')?.remove();toast('저장 실패 재현을 해제했어요. 현재 내용을 다시 저장해 주세요.');return;}if(b.dataset.view){const v=b.dataset.view;go(v);return;}
 if(['projects','new','dashboard','details','interview','learning','review','evidence','decision','actions','journal','settings'].includes(a)){go(a);return;}
 if(a==='home'){if(state.user)go('dashboard');return;}
 if(a==='sample')update(s=>{s.user??={id:'demo-user',name:'메이커'};const project=seedSample(s);s.route={view:'dashboard',projectId:project.id};});
 if(a==='open-project'){const project=state.projects.find(p=>p.id===b.dataset.id);go('details',project.id);}
 if(a==='fill-new')update(s=>{s.forms.new={name:SAMPLE.name,description:SAMPLE.description};});
 if(a==='previous')update(s=>{projectById(s,p.id).step=Math.max(0,p.step-1);});
 if(a==='unknown'){update(s=>{const x=projectById(s,p.id);x.draft[QUESTIONS[x.step].key]='아직 모르겠어요';if(x.step===5)s.route.view='review';else x.step++;});}
 if(a==='interview-example')update(s=>{const x=projectById(s,p.id);x.draft[QUESTIONS[x.step].key]=QUESTIONS[x.step].placeholder.replace('예: ','');});
 if(a==='toggle-stats'){showAllStats=!showAllStats;render();}
 if(['lesson','learn-customer','application'].includes(a)){selectedConcept=b.dataset.concept||'customer';quizVariant=0;quizApplication=a==='application';const r=update(s=>{s.forms.quiz={concept:selectedConcept,variant:quizVariant,application:quizApplication};s.route.view='quiz';},false);if(r.ok){restoreQuizResult();render();}}
 if(a==='retry-quiz'){quizVariant=1;const r=update(s=>{s.forms.quiz={concept:selectedConcept,variant:quizVariant,application:quizApplication};},false);if(r.ok){restoreQuizResult();render();}}
 if(a==='replay-reward'&&lastReward){const previous=lastReward;$('#reward')?.close();reward(previous.title,previous.message,previous.rows);}
 if(a==='close-reward')$('#reward')?.close();
 if(a==='fill-evidence')update(s=>{projectById(s,p.id).uiDraft.evidence={kind:'field',stat:'customer',source:'가상 고객 A',date:new Date().toISOString().slice(0,10),method:'최근 팀플 경험을 묻는 가상 인터뷰',summary:'팀원을 모집하는 일보다 역할 합의와 무임승차가 더 어려웠다고 했어요.',interpretation:'모집보다 팀 안의 역할 합의를 먼저 살펴볼 필요가 있어요.',limitations:'가상 사례이며 한 사람의 경험만 가정했어요.',assessment:'refuted',comparison:''};});
 if(a==='edit-evidence'){pendingEvidence=null;render();}
 if(a==='confirm-evidence'){const pending=pendingEvidence;const r=update(s=>{const result=commitEvidence(s,p.id,pending);if(!result.duplicate)finishFieldTask(s,p.id,pending);projectById(s,p.id).uiDraft.evidence={};if(pending.taskId)projectById(s,p.id).uiDraft[evidenceDraftKey(pending.taskId)]={};s.route.view=p.fieldTasks?.find(t=>t.id===pending.taskId)?.concept==='strategy'?'decision':'dashboard';return result;});if(r.ok){if(!r.result.duplicate)track('evidence_save',{kind:pending.kind},TRACK);pendingEvidence=null;reward(r.result.duplicate?'이미 남긴 기록이에요.':pending.assessment==='refuted'?'생각과 다른 단서를 찾았어요.':'아이디어에 단서가 쌓였어요.',r.result.duplicate?'기존 기록을 유지했어요. 추가 성장이나 보상은 없어요.':pending.kind==='simulation'?'AI 시뮬레이션은 연습이에요. 실제 고객 검증으로 계산하지 않아요.':pending.assessment==='refuted'?'탐구는 진전됐고, 기존 가설은 다시 살펴봐야 해요.':'관찰한 내용과 해석을 구분해 기록했어요.',r.result.rewards);}}
 if(a==='suggest-action')update(s=>{projectById(s,p.id).uiDraft.action={title:'고객 한 명에게 최근 경험 물어보기',criterion:'모집보다 다른 불편이 크다면 문제 가설을 수정한다.'};});
 if(a==='defer-action'){update(s=>{const x=projectById(s,p.id);if(x.nextAction)x.nextAction.status='deferred';s.route.view='dashboard';});toast('잠시 보류했어요. 준비되면 다시 선택할 수 있어요.');}
 if(a==='backup'){const blob=new Blob([storage.raw()||JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='vencubator-demo-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(a==='logout')update(s=>{s.user=null;s.route={view:'welcome',projectId:s.route.projectId};});
 if(a==='reset'){if(confirm('이 브라우저에 저장된 Vencubator 기록을 모두 지울까요? 백업하지 않은 기록은 되돌릴 수 없어요.')){storage.reset();state=blankStore();loadError='';saveFault=false;render();}}
});
render();
